resources:
- name: tutorial
  type: git
  source:
    uri: https://github.com/ibohalsinghkoijam/concourse-docker-images.git
    branch: master

- name: olive-concourse-docker-image
  type: docker-image
  source:
    email: ((email))
    username: ((username))
    password: ((password))
    repository: ((username))/concourse-sample

jobs:
- name: publish
  public: true
  plan:
  - get: tutorial
  - put: olive-concourse-docker-image
    params:
      build: tutorial/docker
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((username))/concourse-sample
      run:
        path: /bin/hello-world
        args: []
      params:
        NAME: ((username))
