resources:
- name: tutorial
  type: git
  source:
    uri: https://github.com/ibohalsinghkoijam/concourse-docker-images.git
    branch: master

- name: hello-world-docker-image
  type: docker-image
  source:
    email: koijam@olivetech.net
    username: ibohal1802
    password: myishika0509
    repository: ibohal1802/concourse-demo-olive

jobs:
- name: publish
  public: true
  plan:
  - get: tutorial
  - put: hello-world-docker-image
    params:
      build: concourse-docker-images/docker
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ibohal1802/concourse-demo-olive
      run:
        path: /bin/hello-world
        args: []
      params:
        NAME: ibohal1802